version: 2
jobs:
  build:
    working_directory: ~/pysst
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install nmap
      - run:
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install .
      - run:
          command: |
            source venv/bin/activate
            pysst --features examples/

